BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello1] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello2] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello3] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello4] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello5] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Boleta] ALTER COLUMN [sello6] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
