BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello1] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello2] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello3] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello4] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello5] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Tolva] ALTER COLUMN [Sello6] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
